### ISSUE TITLE
axes swapped

### ISSUE THREAD

**Issue by bkw** [usefulthink/nodecopter-monitor#4]
At least with my drone, the axes of the new model are swapped: When I move the "nose" (the side with the forward facing camera) downwards, in the visualization the other end goes down. When I tilt it to the right, the model tilts to the left.

Anyway: Awwwwweeeeeesoommmmmmme!

**Comment by usefulthink** [comment]
thanks a lot :)

we haven't quite figured out why this is happening. Must have something to do with different referential systems, wrap-arounds [-π, +π] vs. [0, 2π] or something. Can you fiddle around with the rotation-assignments in [public/webgl.html, Line 263](https://github.com/usefulthink/nodecopter-monitor/blob/master/public/webgl.html#L263) and report which setting works for you? What is your initial value for `navdata.demo.clockwiseDegrees`?

**Comment by bkw** [comment]
will do. Just had to leave my drone. Will report later.

**Comment by bkw** [comment]
I haven't played with the source yet, but these are my navdata observations:
- frontBackDegrees goes negative when the nose faces downwards, and positive when facing up.
- leftRightDegrees goes negative when I tilt the left side downwards and positive when the left faces up.
- clockwiseDegrees starts with a reading of about 0 when the drone powers up.
